curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part0.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part1.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part2.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part3.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part4.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part5.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part6.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part7.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part8.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part9.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part10.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part11.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part12.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part13.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part14.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part15.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part16.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part17.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part18.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part19.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part20.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part21.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part22.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part23.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part24.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part25.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part26.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part27.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part28.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part29.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part30.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part31.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part32.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part33.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part34.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part35.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part36.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part37.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part38.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part39.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part40.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part41.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part42.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part43.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part44.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part45.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part46.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part47.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part48.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part49.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part50.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part51.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part52.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part53.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part54.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part55.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part56.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part57.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part58.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part59.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part60.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part61.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part62.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part63.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part64.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part65.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part66.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part67.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part68.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part69.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part70.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part71.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part72.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part73.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part74.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part75.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part76.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part77.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part78.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part79.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part80.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part81.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part82.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part83.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part84.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part85.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part86.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part87.pickle
# curl http://localhost:6800/schedule.json -d project=guba_spiders -d spider=guba -d fname=part88.pickle
